//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodax.Sections.ShoppingCartMini {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShoppingCartMiniSectionLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShoppingCartMiniSectionLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodax.Sections.ShoppingCartMini.ShoppingCartMiniSectionLocators", typeof(ShoppingCartMiniSectionLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[@class=&apos;hd-cartDropdown__item js-hd-cartDropdown__item&apos;].
        /// </summary>
        internal static string ChoppingCartProductList {
            get {
                return ResourceManager.GetString("ChoppingCartProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[contains(@data-qa,&apos;cartPageItemQuantity__decrease&apos;)].
        /// </summary>
        internal static string MinusButtonsList {
            get {
                return ResourceManager.GetString("MinusButtonsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[contains(@data-qa,&apos;cartPageItemQuantity__increase&apos;)].
        /// </summary>
        internal static string PlusButtonsList {
            get {
                return ResourceManager.GetString("PlusButtonsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-qa-total].
        /// </summary>
        internal static string TotalAmountLabel {
            get {
                return ResourceManager.GetString("TotalAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@data-qa=&apos;headerShoppingCartPopUpShoppingCartPageLink&apos;].
        /// </summary>
        internal static string VIewShoppingCartButton {
            get {
                return ResourceManager.GetString("VIewShoppingCartButton", resourceCulture);
            }
        }
    }
}
