//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodax.Pages.Main {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainPageLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPageLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodax.Pages.Main.MainPageLocators", typeof(MainPageLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@data-qa=&apos;cookiesAgreementAcceptBtn&apos;].
        /// </summary>
        internal static string AcceptAllButton {
            get {
                return ResourceManager.GetString("AcceptAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[contains(@class,&apos;buttonAddToCart&apos;) and @type=&apos;button&apos;].
        /// </summary>
        internal static string DataProductButtonList {
            get {
                return ResourceManager.GetString("DataProductButtonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-product-name].
        /// </summary>
        internal static string DataProductNameList {
            get {
                return ResourceManager.GetString("DataProductNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-product-price].
        /// </summary>
        internal static string DataProductPriceList {
            get {
                return ResourceManager.GetString("DataProductPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ft-copyright&apos;].
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@data-qa=&apos;paginationLinkActive&apos;].
        /// </summary>
        internal static string PaginationAvtivePageButton {
            get {
                return ResourceManager.GetString("PaginationAvtivePageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@data-qa=&apos;paginationLinkPrev&apos;].
        /// </summary>
        internal static string PaginationBackButton {
            get {
                return ResourceManager.GetString("PaginationBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@data-qa=&apos;paginationLinkNext&apos;].
        /// </summary>
        internal static string PaginationNextButton {
            get {
                return ResourceManager.GetString("PaginationNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@data-qa=&apos;paginationLink&apos;].
        /// </summary>
        internal static string PaginationNumericButtonList {
            get {
                return ResourceManager.GetString("PaginationNumericButtonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-qa=&apos;searchResultPageContent&apos;].
        /// </summary>
        internal static string SearchResultPageContentList {
            get {
                return ResourceManager.GetString("SearchResultPageContentList", resourceCulture);
            }
        }
    }
}
